# Generated by Django 4.1.4 on 2023-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='pattern',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
