# Generated by Django 4.1.4 on 2023-01-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_crypto_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='pattern',
        ),
        migrations.AddField(
            model_name='crypto',
            name='price1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='price2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='price3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='price4',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='price5',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
