# Generated by Django 4.1.4 on 2023-01-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_crypto_price1_alter_crypto_price2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='trend',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
