# Generated by Django 4.1.4 on 2023-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_crypto_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='trend',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
