# Generated by Django 4.1.4 on 2023-01-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_crypto_price6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='price6',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
